# Generated by Django 4.1.5 on 2023-01-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('memo', models.TextField()),
            ],
        ),
    ]
