# Generated by Django 4.1.5 on 2023-01-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('writer', models.TextField()),
                ('content', models.TextField()),
                ('hit', models.IntegerField()),
            ],
        ),
    ]
