# Generated by Django 4.1.5 on 2023-01-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
